version: "3.9"
services:

  nginx:
    image: nginx:alpine
    working_dir: /etc/nginx
    volumes:
    - ./${PROJECT_NAME-./app}:/app
    - ./config/xhprof:/xhprof
    - ./config/nginx:/etc/nginx/conf.d
    - ./config/ssl:/etc/nginx/ssl
    - ./logs/nginx:/var/log/nginx
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    restart: always
    networks:
      docker:
        aliases:
          - ${PROJECT_NAME}

  php-fpm:
    build:
      context: "./images/${PHP_VERSION}"
    container_name: "${PROJECT_NAME}-php${PHP_VERSION}"
    working_dir: /app
    volumes:
    - ./${PROJECT_NAME-./app}:/app
    - ./config/xhprof:/xhprof
    - ./config/php/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    - ./config/ssl:/etc/ssl/certs/local
    - ./backups:/backups/
    networks:
        - docker

  db:
    build:
      context: "./images/${MYSQL_VERSION}"
    container_name: "${PROJECT_NAME}-${MYSQL_VERSION}"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    networks:
        - docker

  adminer:
    image: adminer:fastcgi
    networks:
        - docker

  mail:
    image: mailhog/mailhog
    tty: true
    ports:
      - '8025:8025'
    networks:
        - docker
  redis:
    container_name: "${PROJECT_NAME}-redis"
    image: redis:latest
    ports:
      - "127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379"

networks:
  docker:
